chat/urls.py
from django.urls import path, include
from . import views

from django.conf.urls.static import static
from online_courses import settings


urlpatterns = [
    path(r'dialog/', views.DialogsView.as_view(), name='dialogs'),
    path(r'dialogs/create/<user_id>/', views.CreateDialogView.as_view(), name='create_dialog'),
    path(r'dialog/<int:chat_id>/', views.MessagesView.as_view(), name='messages'),
]

course/urls.py
from django.urls import path, include
from . import views

from django.conf.urls.static import static
from online_courses import settings
from .views import pageNotFound, CourseAPIView

# app_name = 'course'

urlpatterns = [
    path('notifications/', views.student_notifications_list, name='notifications_students'),
    path('course_catalog/', views.CatalogCourses.as_view(), name='catalog'),
    path('instructor_courses/', views.СoursesРarticularTeacher.as_view(), name='index'),
    path(r'instructor_courses/edit_course/<int:id>/', views.edit_course, name='edit'),
    path('delete/<int:id>/', views.delete_course, name='delete'),
    path('view_course/<int:id>/', views.view_course, name='view_course'),
    path('<int:c_id>/chat/dialog/', views.dialog, name='dialog'),
    path('<int:id>/chat/', include('chat.urls'), name='chat'),
    path('pass_course/<int:id>/', views.pass_course, name='pass_course'),
    path('<int:id>/info', views.info_course, name='info'),

    path('<int:id>/notifications', views.notifications_list_course, name='notifications_list'),

    # path('<int:id>/students_list/create_notification/<int:s_id>/', views.create_notification, name='create_notification'),

    path('<int:id>/students_list/', views.StudentList.as_view(), name="students_list"),
    #path('create_notification/<int:s_id>/', views.create_notification, name='create_notification'),

    path('<int:id>/grades_list/', views.grades_list, name='grades_list'),
    path('main_settings/<int:id>/', views.settings_edit, name='setting'),
    path('<int:id>/module/', include('module.urls'), name='module'),
    path('<int:id>/check_list/', views.check_list, name='check_list'),
    path('<int:id>/announcement_list/', views.announcement_list, name='announcement_list'),
    path('<int:id>/enrollments/', views.EnrollmentView.as_view(), name='enrollments'),
    path('<int:id>/add_studnet_enrollments/', views.add_student_in_enrollment, name='add_student_in_enrollment'),
    path('<int:id>/delete_student_in_enrollment/', views.delete_student_in_enrollment, name='delete_student_in_enrollment'),
    path('<int:id>/announcement_list/create_announcement/', views.create_announcement, name='create_announcement'),
    path('edit_announcements/<int:id>/', views.edit_announcements, name='announcements_edit'),
    path('create_announcement/', views.create_announcement, name='create_announcement'),

    path('delete_announcements/<int:id>/', views.delete_announcements, name='announcements_delete'),
    path('<int:id>/comments_list/', views.CommentView.as_view(), name='comments_list'),
    path('api/v1/courselist/', CourseAPIView.as_view()),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = pageNotFound








# urlpatterns = [
#     #path('', views.index, name='index'),
#     path('notifications/', views.student_notifications_list, name='notifications_students'),
#
#     path('course_catalog/', views.CatalogCourses.as_view(), name='catalog'),
#     path('instructor_courses/', views.СoursesРarticularTeacher.as_view(), name='index'),
#     path(r'instructor_courses/edit_course/<int:id>/', views.edit_course, name='edit'),
#     path('delete/<int:id>/', views.delete_course, name='delete'),
#     path('view_course/<int:id>/', views.view_course, name='view_course'),
#
#     path('<int:c_id>/chat/dialog/', views.dialog, name='dialog'),
#
#     path('<int:id>/chat/', include('chat.urls'), name='chat'),
#     path('pass_course/<int:id>/', views.pass_course, name='pass_course'),
#     path('<int:id>/info', views.info_course, name='info'),
#
#     path('<int:id>/notifications', views.notifications_list_course, name='notifications_list'),
#     path('<int:id>/students_list/create_notification/<int:s_id>/', views.create_notification, name='create_notification'),
#
#     # path('dialogs/<int:d>/', views.dialog, name='dialog'),
#     path('<int:id>/students_list/', views.students_list, name="students_list"),
#     path('create_notification/<int:id>/', views.create_notification, name='create_notification'),
#
#     # p
#     path('<int:id>/grades_list/', views.grades_list, name='grades_list'),
#
#     # path('create_course/', views.create_course),
#     path('main_settings/<int:id>/', views.settings_edit, name='setting'),
#     path('<int:id>/module/', include('module.urls'), name='module'),
#     path('<int:id>/check_list/', views.check_list, name='check_list'),
#
#     # announcements
#     path('<int:id>/announcement_list/', views.announcement_list, name='announcement_list'),
#
#     path('<int:id>/enrollments/', views.EnrollmentView.as_view(), name='enrollments'),
#
#     path('<int:id>/add_studnet_enrollments/', views.add_student_in_enrollment, name='add_student_in_enrollment'),
#     path('<int:id>/delete_student_in_enrollment/', views.delete_student_in_enrollment, name='delete_student_in_enrollment'),
#
#
#     path('<int:id>/announcement_list/create_announcement/', views.create_announcement, name='create_announcement'),
#     path('edit_announcements/<int:id>/', views.edit_announcements, name='announcements_edit'),
#     path('delete_announcements/<int:id>/', views.delete_announcements, name='announcements_delete'),
#
#     path('<int:id>/comments_list/', views.CommentView.as_view(), name='comments_list'),
#     #path('comment/<int:id>/', views.add_comment, name='add_comment'),
#
#     path('api/v1/courselist/', CourseAPIView.as_view()),
#     #path('module/<int:id>/', views.module_course, name='module'),
# ]

online_courses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("users.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('admin/', admin.site.urls),
    path('courses/', include('course.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)





# path('accounts/', include('django.contrib.auth.urls')),
# path('accounts/', include('django.contrib.auth.urls')),
# path('users/', include('users.urls')),

module/models.py
from django.db import models

# Create your models here.
from tinymce.models import HTMLField

import course.models
from users.models import User


class Module(models.Model):
    course = models.ForeignKey("course.Course", on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    # description = models.TextField(null=True, blank=True)  # empty values
    update = models.DateTimeField(auto_now=True)
    create = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('id',)
        db_table = 'module'
        verbose_name = 'Модуль',
        verbose_name_plural = 'Модули'

    def __str__(self):
        return self.title


class Lesson(models.Model):
    module = models.ForeignKey(Module, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    update = models.DateTimeField(auto_now=True)
    create = models.DateTimeField(auto_now_add=True)
    short_description = models.TextField(max_length=250)
    description = models.TextField(null=True, blank=True)
    is_published = models.BooleanField(null=True, default=False)

    class Meta:
        ordering = ('id',)
        db_table = 'lesson'
        verbose_name = 'Урок',
        verbose_name_plural = 'Уроки'

    def __str__(self):
        return self.title


class Block(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    text_content = models.TextField(null=True, blank=True)
    title = models.CharField(max_length=200, null=True)
    update = models.DateTimeField(auto_now=True)
    # level = models.IntegerField(null=False)
    create = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('id',)
        db_table = 'block'
        verbose_name = 'Блок урока',
        verbose_name_plural = 'Блоки урока'

    def __str__(self):
        return self.title


# class Text(models.Model):
#     content = models.TextField(null=True, blank=True)
#     time_update = models.DateTimeField(auto_now=True)
#     time_create = models.DateTimeField(auto_now_add=True)
#     # block = models.ForeignKey(Block, on_delete=models.CASCADE)
#
#     class Meta:
#         ordering = ('id',)
#         db_table = 'text'
#         verbose_name = 'Текс',
#         verbose_name_plural = 'Текста'
#
#     def __str__(self):
#         return self.content


class File(models.Model):
    block = models.ForeignKey(Block, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    file = models.FileField(upload_to='files/%Y-%m-%d/', null=True, blank=True)
    time_update = models.DateTimeField(auto_now=True)
    time_create = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('id',)
        db_table = 'files'
        verbose_name = 'Файл',
        verbose_name_plural = 'Файлы'

    def __str__(self):
        return self.title


class UrlLink(models.Model):
    block = models.ForeignKey(Block, on_delete=models.CASCADE)
    title = models.CharField(max_length=250, null=True)
    url = models.URLField(max_length=200)
    time_update = models.DateTimeField(auto_now=True)
    time_create = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('id',)
        db_table = 'url'
        verbose_name = 'Ссылка',
        verbose_name_plural = 'Ссылки'

    def __str__(self):
        return self.title


class Task(models.Model):
    module = models.ForeignKey(Module, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    time_create = models.DateTimeField(auto_now_add=True)
    time_deadline = models.DateTimeField(null=True)
    file = models.FileField(upload_to='files/%Y-%m-%d/', null=True, blank=True)

    class Meta:
        ordering = ('id',)
        db_table = 'task'
        verbose_name = 'Задание',
        verbose_name_plural = 'Задания'

    def __str__(self):
        return self.title


class StudentAnswer(models.Model):
    task = models.ForeignKey(Task, on_delete=models.SET_NULL, null=True)
    student = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    description = models.TextField(null=True, blank=True)
    file = models.FileField(upload_to='files/%Y-%m-%d/', null=True, blank=True)
    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('id',)
        db_table = 'student_answer'
        verbose_name = 'Ответ на задание',
        verbose_name_plural = 'Ответы на задания'

    def __str__(self):
        return self.student.email


class Mark(models.Model):
    answer = models.OneToOneField(StudentAnswer, on_delete=models.SET_NULL, null=True)
    student = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    course = models.ForeignKey("course.Course", on_delete=models.CASCADE)
    time_create = models.DateTimeField(auto_now_add=True)
    mark = models.IntegerField(null=True)

    class Meta:
        ordering = ('id',)
        db_table = 'mark'
        verbose_name = 'Оценка',
        verbose_name_plural = 'Оценки'

    def __str__(self):
        return self.mark


class Announcement(models.Model):
    course = models.ForeignKey("course.Course", on_delete=models.CASCADE)
    content = models.TextField(blank=True)
    # description = models.TextField(null=True, blank=True)  # empty values
    time_update = models.DateTimeField(auto_now=True)
    time_create = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('id',)
        db_table = 'announcement'
        verbose_name = 'Обявление',
        verbose_name_plural = 'Объявление'

    def __str__(self):
        return self.content

course/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget

from course.models import Comment, Notifications, CoursEnrollment
from bootstrap_datepicker_plus.widgets import DatePickerInput, TimePickerInput, DateTimePickerInput, MonthPickerInput, YearPickerInput


class CourseForm(forms.Form):
    title = forms.CharField(max_length=64, min_length=4, label='')
    description = forms.CharField(max_length=200, label='',
                                  widget=forms.Textarea(attrs={'rows': 3}),
                                  required=False)


class NotificationForm(forms.Form):
    content = forms.CharField(max_length=200, label='',
                                  widget=forms.Textarea(attrs={'rows': 2}),
                                  required=False)


class NotificationFormCreate1(forms.Form):
    student_id = forms.IntegerField(
        widget=forms.HiddenInput,
        required=False
    )
    content = forms.CharField(
        label="",
        widget=forms.Textarea(attrs={'rows': 3})
    )


class NotificationFormCreate(forms.ModelForm):
    class Meta:
        model = Notifications
        fields = ("content",)



class SettingsForm(forms.Form):
    learning_format = forms.CharField(required=False, max_length=200, min_length=4, label='')
    will_learn = forms.CharField(required=False, label='',
                                 widget=forms.Textarea(attrs={'rows': 3}))
    necessary_training = forms.CharField(required=False, label='',
                                         widget=forms.Textarea(attrs={'rows': 3}))

    subject = forms.CharField(required=False, max_length=200, min_length=4, label='')
    language = forms.CharField(required=False, max_length=200, min_length=4, label='')
    image = forms.ImageField(required=False, label='')
    is_published = forms.BooleanField(required=False, label='Опубликован')

    about_course = forms.CharField(required=False, label='',
                                   widget=SummernoteWidget(attrs={'rows': 4,
                                    'summernote': {'width': '100%'}}
                                   ))

    how_training = forms.CharField(required=False, label='',  widget=SummernoteWidget(attrs={'rows': 4,
                                    'summernote': {'width': '100%'}}
                                   ))
    what_you_get = forms.CharField(required=False, label='',  widget=SummernoteWidget(attrs={'rows': 4,
                                    'summernote': {'width': '100%'}}
                                   ))
    LEVEL_CHOICES = (
        ('1', u"для начаниющих"),
        ('2', u"для продолжающих"),
        ('3', u"для продвинутых"),
    )
    level = forms.ChoiceField(label='', choices=LEVEL_CHOICES, required=False)

    COURSE_CHOICES = (
        ('0', u"идет разработка курса"),
        ('1', u"идет набор на курс"),
        ('2', u"курс начался"),
        ('3', u"курс закончился"),
    )
    active_level = forms.ChoiceField(label='', choices=COURSE_CHOICES, required=False)


class CoursEnrollmentForm(forms.Form):
    time_create = forms.DateTimeField(input_formats=['%Y-%m-%d %H:%M'], required=False, label='Дата начала набора:')
    time_end = forms.DateTimeField(input_formats=['%Y-%m-%d %H:%M'], required=False, label='Дата окончания набора:')

#forms.DateField(widget=DateTimePickerInput(),)


class CommentForm1(forms.Form):
    parent_comment = forms.IntegerField(
        widget=forms.HiddenInput,
        required=False
    )
    comment_area = forms.CharField(
        label="",
        widget=forms.Textarea(attrs={'rows': 3})
    )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("content",)

course/templates/course/pass_course/info_course.html
{% extends "C:\Users\User\PycharmProjects\online_courses\course\templates\course\base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/style_index.css'%}" type="text/css">



{% block content %}

    <section class="container py-3">
        <div class="bd-example">
            <nav>
                <div class="nav nav-tabs mb-3" id="nav-tab" role="tablist">
                    <button class="nav-link active" id="nav-mark-tab" data-bs-toggle="tab"
                            data-bs-target="#nav-mark" type="button" role="tab" aria-controls="nav-mark"
                            aria-selected="true">Информация о курсе</button>
                    <button class="nav-link" id="nav-progress-tab" data-bs-toggle="tab"
                            data-bs-target="#nav-progress" type="button" role="tab" aria-controls="nav-progress"
                            aria-selected="false">Инструктор курса</button>
              </div>
            </nav>
            <div class="tab-content" id="nav-tabContent">
                <div class="tab-pane fade show active" id="nav-mark" role="tabpanel" aria-labelledby="nav-mark-tab">

                     <div class="container">
                        <div class="main-body">

                             <div class="col-sm-12 mb-3">
                                <div class="card h-100">
                                    <div class="card-body">
                                        <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2"></i>
                                            Название курса: {{ course.title }}</h6>
                                        <p class="text-sm text-secondary">{{ course.settings.learning_format }}</p>

                                        <p>{{ course.description }}</p>
                                    </div>
                                </div>
                             </div>

                            <div class="row px-3">
                                <div class="col-sm-4 mb-3">
                                    <div class="card h-100">
                                        <div class="card-body">
                                            <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2"></i>
                                                Требуемый уровень подготовки </h6>
                                            <p class="text-sm text-secondary">Для продолжающих</p>
                                        </div>
                                    </div>
                                </div>
                                 <div class="col-sm-4 mb-3">
                                    <div class="card h-100">
                                        <div class="card-body">
                                            <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2"></i>
                                                Язык курса </h6>
                                            <p class="text-sm text-secondary">{{ course.settings.language }}</p>
                                        </div>
                                    </div>
                                </div>
                                 <div class="col-sm-4 mb-3">
                                    <div class="card h-100">
                                        <div class="card-body">
                                            <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2"></i>
                                                Предмет курса </h6>
                                            <p class="text-sm text-secondary">{{ course.settings.subject }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="col-sm-12 mb-3">
                                <div class="card h-100">
                                    <div class="card-body">
                                        <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2"></i>
                                            О курсе </h6>
                                        <p class="text-secondary">{{ course.settings.about_course | safe }}</p>
                                    </div>
                                </div>
                             </div>

                            <div class="col-sm-12 mb-3">
                                <div class="card h-100">
                                    <div class="card-body">
                                        <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2"></i>
                                            Необходимая подготовка </h6>
                                        <p class="">{{ course.settings.necessary_training | safe }}</p>
                                    </div>
                                </div>
                             </div>

                            <div class="col-sm-12 mb-3">
                                <div class="card h-100">
                                    <div class="card-body">
                                        <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2"></i>
                                            Как проходит обучение </h6>
                                        <p class="text-sm text-secondary">{{ course.settings.how_training | safe }}</p>
                                    </div>
                                </div>
                             </div>


                             <div class="col-sm-12 mb-3">
                                <div class="card h-100">
                                    <div class="card-body">
                                        <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2"></i>
                                            Почему имеено мы </h6>
                                        <p class="text-sm text-secondary">{{ course.settings.what_you_get | safe }}</p>
                                    </div>
                                </div>
                             </div>
                        </div>
                     </div>


                </div>


                <div class="tab-pane fade" id="nav-progress" role="tabpanel" aria-labelledby="nav-progress-tab">


                    <div class="container">
    <div class="main-body">

          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                      {% if course.author.image_pic.url %}
                          <img src="{{ course.author.image_pic.url }}"
                         alt="Admin" class="rounded-circle" width="150" height="150">
                      {% else %}
                      {% endif %}

                    <div class="mt-3">
                      <h4>{{ course.author.username }}</h4>
{#                      <p class="text-secondary mb-1">Full Stack Developer</p>#}
{#                      <p class="text-muted font-size-sm">Bay Area, San Francisco, CA</p>#}

                    </div>
                  </div>
                </div>
              </div>
{#              <div class="card mt-3">#}
{#                <div class="card-body text-dark">#}
{#                      <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">#}
{#                          </i>Ваши курсы</h6>#}
{#                            {% for item in courses_instructor %}#}
{#                                {{ item.title }}#}
{#                            {% endfor %}#}
{#                    </div>#}
{#              </div>#}
            </div>
            <div class="col-md-8 py-3">
                  <div class="row">
                    <div class="col">
                      <h6 class="mb-0">Имя пользователя</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ course.author.username }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ course.author.email }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col">
                      <h6 class="mb-0">Телефон</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      + 375 (29) 111-22-33
                    </div>
                  </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                          <h6 class="mb-0">Адрес</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                          г. Минск
                        </div>
                      </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">GitHub</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        <a class="text-secondary" href="https://github.com/Yulia-nia"> Yulia-nia</a>
                    </div>
                  </div>

                <div class="row gutters-sm text-dark py-5">
                <div class="col-sm-12 mb-3">
                  <div class="card h-100">
                    <div class="card-body">
                      <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2"></i>
                          О себе</h6>
                            <p> Создаю профессиональные онлайн курсы с 2016 года.
                                Профессионально обучаю работе с графическими редакторами Adobe.
                                Преподаю веб дизайн и верстку.</p>
                    </div>
                  </div>
                </div>

                    <div class="col-sm-12 mb-3">
                  <div class="card h-100">
                    <div class="card-body">
                      <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2"></i>
                          Созданные курсы</h6>
                            {% for item in courses_instructor %}
                                <div class="py-2">
                                <a href="{% url 'info' item.id %}" class="text-secondary"> {{ item.title }} </a>

                                </div>
                            {% endfor %}
                    </div>
                  </div>
                </div>
                </div>




{#              <div class="row gutters-sm text-dark py-5">#}
{#                <div class="col-sm-6 mb-3">#}
{#                  <div class="card h-100">#}
{#                    <div class="card-body">#}
{#                      <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2"></i>#}
{#                          Избранное</h6>#}
{#                        {% for item in courses %}#}
{#                          <p>{{ item.title }}</p>#}
{#                        {% endfor %}#}
{#                    </div>#}
{#                  </div>#}
{#                </div>#}
{#                <div class="col-sm-6 mb-3">#}
{#                  <div class="card h-100">#}
{#                    <div class="card-body">#}
{#                      <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">#}
{#                          </i>Проходите</h6>#}
{#                            {% for i in c_s %}#}
{#                                {{ i.title }}#}
{#                            {% endfor %}#}
{#                    </div>#}
{#                  </div>#}
{#                </div>#}
{#              </div>#}
            </div>
          </div>

        </div>
    </div>

{##}
{#                    <p>{{ instructor.email }}</p>#}
{#                    <p>{{ instructor.username }}</p>#}
{#                    <p>{{ instructor.bio | safe }}</p>#}
                </div>
            </div>
        </div>
    </section>

{% endblock %}

course/templates/course/pass_course/pass_course.html
{% extends "C:\Users\User\PycharmProjects\online_courses\course\templates\course\base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/style_index.css'%}" type="text/css">


{% block content %}

<div class="container">
    <div class="py-3 text-center">
    <p>Теперь вы проходите данный курс</p>
        <p>{{ course.title }}</p>
        <p>{{ course.settings.about_course | safe }}</p>
        {% for module in course.module_set.values %}
            <p>{{ module.title }}</p>
        {%endfor %}
        <p></p>
    </div>
</div>

{% endblock %}